import React from 'react'
import Head from 'next/head'
import Header from './Header'

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-100 min-h-screen dark:bg-gray-800'>
        <Header/>
        {children}
      </div>
    </>
  )
}

export default Layout